Starting val doesn't appear online
psychopy/psychojs pull request #501
Opened 2022-05-24 19:26 UTC by lightest

Starting val doesn't appear online from Bugs with slider online series.

2022-05-24 19:26 UTC, peircej commented
Task linked: [CU-2au7jh3 Starting val doesn't appear online](https://app.clickup.com/t/2au7jh3)

2022-06-09 10:53 UTC, apitiot commented
Awaiting results of comprehensive tests before committing.

2022-06-15 07:23 UTC, apitiot commented on src/visual/Slider.js
> +		const markerVal = Number.isFinite(this._rating) ? this._rating : (Number.isFinite(this._startValue) ? this._startValue : undefined);
Please no nested ternary operator :-P
Other than that, I believe we are good to go.

2022-06-15 07:24 UTC, apitiot requested changes
See comment regarding nested ternary operators.

2022-06-15 12:13 UTC, merged